# ENVIRONMENT IN PYTHON

- In programming, an environment is the setup or context in which your code runs.
- It contains the tools, libraries, settings, and dependencies needed for a program to work.
- It is an isolated workspace where we can install and manage packages without affecting the global Python installation.
- when building software or projects, which version of python we using is important
  for eg.
  if we write some LOC in python 3.10
  the same line may not work in python 3.13
  the developers could hv removed something (deprecated) that LOC

- Libraries get updated all the time

- Dependencies: things/packages/libraries that are required to run a program or making a program work

--> we have already done:

pip install 'requests' 'pillow' 'numpy'

- NumPy : numerical ops
- Pandas : deal wt data manipulation
- Matplotlib : plotting library
- Scikit-lear : machine learning
- Tensorflow or PyTorch : frameworks for deep learning

## NumPy
- numerical python
- gives us a fast data type : called Array or 'ndarray'


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

num_array = np.array([1,2,3,4,5])
print(num_array)
num_array

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [9]:
import numpy as np

num_list = [1,2,3,4,5]
num_array = np.array(num_list)
print(num_array)

num_array

type(num_array) # ndarray is N Dimensional array

[1 2 3 4 5]


numpy.ndarray

In [ ]:
import numpy as np

num_list = [1,2,3,4,5]
num_array = np.array(num_list)
print(num_array)

num_array  # array([1, 2, 3, 4, 5])
print(num_list)

# type(num_array) # ndarray is N Dimensional array

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [12]:
# homogenity of arrays

num_list = [1,2.0,"nomie",4,5]

num_array = np.array(num_list)

num_array

array(['1', '2.0', 'nomie', '4', '5'], dtype='<U32')

In [ ]:
## exercise

## using loop
num_list = [1,2,3,4,5,6,7,8,9]

num_list10 = [x * 10 for x in num_list]
print(num_list10)



[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [25]:
num_list = [1,2,3,4,5,6,7,8,9]

num_list10 = []

for num in num_list:
    num_list10.append(num*10)

print(num_list10)



[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
# using np array

num_array = np.array(num_list)
num_array # array([1, 2, 3, 4, 5, 6, 7, 8, 9])

num_array*10
print(num_array*10)

[10 20 30 40 50 60 70 80 90]


In [32]:
num_4 = np.array([1,2,3,4])
num_3 = np.array([10,10,20,10])

num_4 * num_3

array([10, 20, 60, 40])

In [33]:
num_4 = np.array([1, 2, 3, 4])
num_3 = np.array([10, 10, 20])

num_4 * num_3 # Error: operands could not be broadcast together with shapes (3,) (4,)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# storage for list

pylist = [100,200,300]

print(id(pylist))
print(id(pylist[0]))
print(id(pylist[1]))
print(id(pylist[2]))

2754679463104
140718601287192
140718601290392
2754679295792


In [ ]:
# storage for array

pylist = np.array([100,200,300])

print(id(pylist))
print(id(pylist[0]))
print(id(pylist[1]))
print(id(pylist[2]))

2754679976272
2754663608752
2754663608752
2754663608752


In [39]:
np_arr = np.array([100,200,300,400], dtype = np.int64)
np_arr.ctypes.data
print(id(np_arr))
print(id(np_arr[0]))
print(id(np_arr[1]))
print(id(np_arr[2]))
print(id(np_arr[3]))


2754679978768
2754679301392
2754679301392
2754679301392
2754679301392
